### ISSUE TITLE
Server-Crash

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands_metaserver#69]
Last night the metaserver descided to crash:

```
Apr 02 04:31:31 widelands.org wlms[2488]: 2020/04/02 04:31:31 Empty data stream for client . Will disconnect
Apr 02 04:31:37 widelands.org wlms[2488]: 2020/04/02 04:31:37 Empty data stream for client . Will disconnect
Apr 02 04:31:42 widelands.org wlms[2488]: 2020/04/02 04:31:42 Empty data stream for client . Will disconnect
Apr 02 04:31:47 widelands.org wlms[2488]: 2020/04/02 04:31:47 Empty data stream for client . Will disconnect
Apr 02 04:31:53 widelands.org wlms[2488]: 2020/04/02 04:31:53 Empty data stream for client . Will disconnect
Apr 02 04:31:53 widelands.org wlms[2488]: 2020/04/02 04:31:53 Error while handling invalid command  from client
Apr 02 04:31:54 widelands.org wlms[2488]: 2020/04/02 04:31:54 Error while handling invalid command  from client
Apr 02 04:31:54 widelands.org wlms[2488]: panic: runtime error: makeslice: len out of range
Apr 02 04:31:54 widelands.org wlms[2488]: goroutine 21191 [running]:
Apr 02 04:31:54 widelands.org wlms[2488]: github.com/widelands/widelands-metaserver/wlms/packet.readString(0x8412ca0, 0xaa8c028, 0xfffffffe, 0x0, 0x0, 0x804febb, 0x8357440)
Apr 02 04:31:54 widelands.org wlms[2488]:         /tmp/metaserver/src/github.com/widelands/widelands-metaserver/wlms/packet/packet.go:142 +0x33
Apr 02 04:31:54 widelands.org wlms[2488]: github.com/widelands/widelands-metaserver/wlms/packet.Read(0x8412ca0, 0xaa8c028, 0xaa8c028, 0x8412ca0, 0xaa8c028)
Apr 02 04:31:54 widelands.org wlms[2488]:         /tmp/metaserver/src/github.com/widelands/widelands-metaserver/wlms/packet/packet.go:69 +0x5c
Apr 02 04:31:54 widelands.org wlms[2488]: main.(*Client).readingLoop(0xa95a540, 0xa98a200, 0xa98a240, 0xa98a280, 0xa98e120, 0xa98e140, 0x8415840, 0xa80f478, 0x0, 0x0, ...)
Apr 02 04:31:54 widelands.org wlms[2488]:         /tmp/metaserver/src/github.com/widelands/widelands-metaserver/wlms/client.go:364 +0x8e
Apr 02 04:31:54 widelands.org wlms[2488]: created by main.DealWithNewConnection
Apr 02 04:31:54 widelands.org wlms[2488]:         /tmp/metaserver/src/github.com/widelands/widelands-metaserver/wlms/client.go:226 +0x9f
Apr 02 04:31:54 widelands.org systemd[1]: wl-metaserver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 02 04:31:54 widelands.org systemd[1]: wl-metaserver.service: Failed with result 'exit-code'.
Apr 02 04:31:54 widelands.org systemd[1]: wl-metaserver.service: Triggering OnFailure= dependencies.
```

**Comment by Notabilis** [comment]
It seems as if ... something was repeatedly connecting and sending random data to both the metaserver and the relay at that time. At some point the data was interpreted as a too large (or negative?) integer which triggered the panic. I will prepare a branch checking the integer sizes, we only need a quite small range of it anyway.

**Comment by Notabilis** [comment]
Fix is merged and deployed.
